name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  check:
    name: Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: julia-actions/setup-julia@v1
        with:
          version: "1.6"

      - uses: extractions/setup-just@v1
        with:
          just-version: "0.10"

      - run: just install

      - run: just check

      - run: just test
